[package]
name = "concat"
version = "26.9.18"
edition = "2024"
authors = ["Elad Karako <eladkarako@gmail.com>"]
description = "join files. optionally with stdin. to stdout or file. see --help ."
license = "MIT"
repository = "https://github.com/eladkarako/concat"
homepage = "https://github.com/eladkarako/concat"
keywords = ["concat", "streaming", "cli"]
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
is-terminal = "0.4.17"

[build-dependencies]
winres = "0.1.12"
toml = "1.1.6"


[profile.release]
opt-level = "z"          # “z” = maximum size reduction (equivalent to -C opt-level=s)
lto = true               # Link‑time optimisation
codegen-units = 1        # Better optimisation (single codegen unit)
panic = "abort"          # Remove unwinding tables
debug = false            # No debug info
strip = true             # Strip symbols (requires rustc 1.56+)
rpath = false            # Don't embed runtime library paths
incremental = false      # Disable incremental compilation (cleaner builds)


